package main

import (
	"fmt"
	"log"
	"time"

	"github.com/xuri/excelize/v2"
)

func main() {
	f, err := excelize.OpenFile("template.xlsx") // file sits next to main.go
	if err != nil {
		log.Fatalf("open template: %v", err)
	}
	defer func() { _ = f.Close() }()

	// We expect these two tabs to exist exactly as named:
	want := []string{"Week 1", "Week 2"}

	// Verify they exist (helpful if there’s a typo or extra spaces)
	have := f.GetSheetList()
	ok := map[string]bool{}
	for _, s := range have {
		ok[s] = true
	}
	for _, s := range want {
		if !ok[s] {
			log.Fatalf("sheet %q not found; sheets present: %v", s, have)
		}
	}

	// Write something simple you can see; change cells later to your real fields
	now := time.Now().Format("2006-01-02 15:04")
	for _, s := range want {
		must(f.SetCellValue(s, "A1", "Generated by Go"))
		must(f.SetCellValue(s, "A2", "Run at: "+now))
		// Example placeholders you can change once A1/A2 show up:
		// must(f.SetCellValue(s, "B4", "Kai Company Inc."))
		// must(f.SetCellValue(s, "E4", "INV-2025-001"))
	}

	if err := f.SaveAs("output.xlsx"); err != nil {
		log.Fatalf("save: %v", err)
	}
	fmt.Println("Wrote output.xlsx")
}

func must(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
